In [ ]:
import numpy as np
import pandas as pd


In [ ]:
dic1={
    "name":["harry","rohan","skillf","shubh"],
    "marks":[92,34,24,17],
    "city":['rampur',"kolkata","bareily",'antartica']
}

In [ ]:
df=pd.DataFrame(dic1)

In [ ]:
df

name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24    bareily
3   shubh     17  antartica

In [ ]:
df.to_csv("friends.csv")

In [ ]:
df.to_csv("friends.csv_indexfalse", index=False)


In [ ]:
df.head(2)

name  marks     city
0  harry     92   rampur
1  rohan     34  kolkata

In [ ]:
df.tail(2)

name  marks       city
2  skillf     24    bareily
3   shubh     17  antartica

In [ ]:
df.describe

<bound method NDFrame.describe of      name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24    bareily
3   shubh     17  antartica>

In [ ]:
df.describe()

marks
count   4.00000
mean   41.75000
std    34.21866
min    17.00000
25%    22.25000
50%    29.00000
75%    48.50000
max    92.00000

In [ ]:
df.to_csv("test1.csv")

In [ ]:
harry=pd.read_csv("test1.csv")

In [ ]:
harry


Unnamed: 0    name  marks       city
0           0   harry     92     rampur
1           1   rohan     34    kolkata
2           2  skillf     24    bareily
3           3   shubh     17  antartica

In [ ]:
harry["marks"]

0    92
1    34
2    24
3    17
Name: marks, dtype: int64

In [ ]:
harry["marks"][0]

92

In [ ]:
harry["marks"][0]=50

<ipython-input-16-6a2001e2b664>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harry["marks"][0]=50


In [ ]:
harry


Unnamed: 0    name  marks       city
0           0   harry     50     rampur
1           1   rohan     34    kolkata
2           2  skillf     24    bareily
3           3   shubh     17  antartica

In [ ]:
harry.to_csv("harry.csv")

In [ ]:
harry.index=["i","ii",'iii','iv']

In [ ]:
harry

Unnamed: 0    name  marks       city
i             0   harry     50     rampur
ii            1   rohan     34    kolkata
iii           2  skillf     24    bareily
iv            3   shubh     17  antartica

In [ ]:
ser=pd.Series(np.random.rand(34))

In [ ]:
ser

0     0.790406
1     0.698265
2     0.525663
3     0.708377
4     0.044820
5     0.578925
6     0.396497
7     0.281354
8     0.672204
9     0.325228
10    0.513565
11    0.751550
12    0.087684
13    0.332990
14    0.920335
15    0.381279
16    0.169844
17    0.280981
18    0.801469
19    0.334492
20    0.239444
21    0.792551
22    0.906957
23    0.055060
24    0.181725
25    0.187350
26    0.908240
27    0.086713
28    0.112029
29    0.128818
30    0.254831
31    0.470096
32    0.026594
33    0.134827
dtype: float64

In [ ]:
type(ser)

pandas.core.series.Series

In [ ]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [ ]:
newdf

0         1         2         3         4
0    0.148949  0.911063  0.408980  0.841196  0.019471
1    0.610237  0.477117  0.915987  0.840819  0.746444
2    0.286369  0.919387  0.769584  0.047926  0.333141
3    0.806480  0.365636  0.898958  0.983921  0.036964
4    0.293454  0.024477  0.706326  0.950589  0.313468
..        ...       ...       ...       ...       ...
329  0.767511  0.935906  0.730144  0.573351  0.041465
330  0.549862  0.156203  0.817324  0.294024  0.831850
331  0.433503  0.703824  0.012962  0.341234  0.182303
332  0.777378  0.264590  0.990195  0.103620  0.372196
333  0.677424  0.515871  0.769076  0.456608  0.929087

[334 rows x 5 columns]

In [ ]:
type(newdf)

pandas.core.frame.DataFrame

In [ ]:
newdf.head()

0         1         2         3         4
0  0.148949  0.911063  0.408980  0.841196  0.019471
1  0.610237  0.477117  0.915987  0.840819  0.746444
2  0.286369  0.919387  0.769584  0.047926  0.333141
3  0.806480  0.365636  0.898958  0.983921  0.036964
4  0.293454  0.024477  0.706326  0.950589  0.313468

In [ ]:
newdf.describe()

0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.518949    0.471996    0.498721    0.487005    0.489915
std      0.273288    0.282605    0.290030    0.301055    0.291964
min      0.006373    0.003582    0.012962    0.000569    0.002221
25%      0.295655    0.229661    0.241899    0.226304    0.223673
50%      0.537559    0.475201    0.510409    0.472396    0.480317
75%      0.754553    0.711731    0.743396    0.753927    0.746506
max      0.998256    0.998272    0.990195    0.999554    0.998126

datatype of each column -can be different

In [ ]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

changing a value in dataframe

In [ ]:
newdf[0][0]="arun"

<ipython-input-32-957c05b3e9b0>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'arun' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]="arun"


In [ ]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [ ]:
newdf.head()

0         1         2         3         4
0      arun  0.911063  0.408980  0.841196  0.019471
1  0.610237  0.477117  0.915987  0.840819  0.746444
2  0.286369  0.919387  0.769584  0.047926  0.333141
3   0.80648  0.365636  0.898958  0.983921  0.036964
4  0.293454  0.024477  0.706326  0.950589  0.313468

index

In [ ]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

 colums and its length

In [ ]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

changinginto numpy array

In [ ]:
newdf.to_numpy()

array([[54, 0.8408194557490928, 0.7464438070035098, nan],
       [54, 0.047925752001012456, 0.33314118801903225, nan],
       [54, 0.9839207394757968, 0.03696367718524207, nan],
       ...,
       [54, 0.3412341212632054, 0.18230333273666466, nan],
       [54, 0.10362025103535277, 0.3721956114638302, nan],
       [54, 0.4566076339845544, 0.9290872522728751, nan]], dtype=object)

In [ ]:
newdf[0][0]=0.3

In [ ]:
newdf.head()

0         1         2         3         4
0       0.3  0.911063  0.408980  0.841196  0.019471
1  0.610237  0.477117  0.915987  0.840819  0.746444
2  0.286369  0.919387  0.769584  0.047926  0.333141
3   0.80648  0.365636  0.898958  0.983921  0.036964
4  0.293454  0.024477  0.706326  0.950589  0.313468

transpose-row change into col and col change into row

In [ ]:
newdf.T

0         1         2         3         4         5         6    \
0       0.3  0.610237  0.286369   0.80648  0.293454  0.899606  0.293742   
1  0.911063  0.477117  0.919387  0.365636  0.024477   0.75656  0.266324   
2   0.40898  0.915987  0.769584  0.898958  0.706326  0.167367  0.761514   
3  0.841196  0.840819  0.047926  0.983921  0.950589  0.531115  0.794848   
4  0.019471  0.746444  0.333141  0.036964  0.313468  0.002221  0.657157   

        7         8         9    ...       324       325       326       327  \
0  0.151984  0.565247  0.239472  ...  0.358864  0.028144  0.236017   0.53164   
1  0.990941  0.515495  0.577444  ...  0.815133  0.415315  0.542311  0.139647   
2  0.108034  0.501921  0.892457  ...  0.665448  0.281591  0.188903  0.623877   
3  0.641589  0.010555  0.473652  ...  0.501181  0.278157  0.425248  0.809904   
4  0.080161  0.123224   0.48457  ...  0.739249  0.654766  0.401448  0.547291   

        328       329       330       331       332       333  
0   0.73081  0.767511  0.549862  0.433503  0.777378  0.677424  
1  0.586736  0.935906  0.156203  0.703824   0.26459  0.515871  
2  0.086545  0.730144  0.817324  0.012962  0.990195  0.769076  
3   0.34866  0.573351  0.294024  0.341234   0.10362  0.456608  
4  0.956289  0.041465   0.83185  0.182303  0.372196  0.929087  

[5 rows x 334 columns]

In [ ]:
newdf.head()

0         1         2         3         4
0       0.3  0.911063  0.408980  0.841196  0.019471
1  0.610237  0.477117  0.915987  0.840819  0.746444
2  0.286369  0.919387  0.769584  0.047926  0.333141
3   0.80648  0.365636  0.898958  0.983921  0.036964
4  0.293454  0.024477  0.706326  0.950589  0.313468

sorting index asscending=false,
by default it is true,
axis0=row  ,
axis1=column

In [ ]:
newdf.sort_index(axis=0,ascending=False)

0         1         2         3         4
333  0.677424  0.515871  0.769076  0.456608  0.929087
332  0.777378  0.264590  0.990195  0.103620  0.372196
331  0.433503  0.703824  0.012962  0.341234  0.182303
330  0.549862  0.156203  0.817324  0.294024  0.831850
329  0.767511  0.935906  0.730144  0.573351  0.041465
..        ...       ...       ...       ...       ...
4    0.293454  0.024477  0.706326  0.950589  0.313468
3     0.80648  0.365636  0.898958  0.983921  0.036964
2    0.286369  0.919387  0.769584  0.047926  0.333141
1    0.610237  0.477117  0.915987  0.840819  0.746444
0         0.3  0.911063  0.408980  0.841196  0.019471

[334 rows x 5 columns]

In [ ]:
newdf.sort_index(axis=1,ascending=False)

4         3         2         1         0
0    0.019471  0.841196  0.408980  0.911063       0.3
1    0.746444  0.840819  0.915987  0.477117  0.610237
2    0.333141  0.047926  0.769584  0.919387  0.286369
3    0.036964  0.983921  0.898958  0.365636   0.80648
4    0.313468  0.950589  0.706326  0.024477  0.293454
..        ...       ...       ...       ...       ...
329  0.041465  0.573351  0.730144  0.935906  0.767511
330  0.831850  0.294024  0.817324  0.156203  0.549862
331  0.182303  0.341234  0.012962  0.703824  0.433503
332  0.372196  0.103620  0.990195  0.264590  0.777378
333  0.929087  0.456608  0.769076  0.515871  0.677424

[334 rows x 5 columns]

eachcolumn of dataframe is a series hence dtaframe is a combination of series

In [ ]:
newdf[0]

0           0.3
1      0.610237
2      0.286369
3       0.80648
4      0.293454
         ...   
329    0.767511
330    0.549862
331    0.433503
332    0.777378
333    0.677424
Name: 0, Length: 334, dtype: object

In [ ]:
type(newdf[0])

pandas.core.series.Series

In [ ]:
newdf.head()

0         1         2         3         4
0       0.3  0.911063  0.408980  0.841196  0.019471
1  0.610237  0.477117  0.915987  0.840819  0.746444
2  0.286369  0.919387  0.769584  0.047926  0.333141
3   0.80648  0.365636  0.898958  0.983921  0.036964
4  0.293454  0.024477  0.706326  0.950589  0.313468

view-isbehave like pointer and point to same databaseor same location,
here newdf2 is a view of newdf,
and any change in newdf2 also brings changes in newdf

In [ ]:
newdf2=newdf

In [ ]:
newdf2[0][0]=9876

In [ ]:
newdf

0         1         2         3         4
0        9876  0.911063  0.408980  0.841196  0.019471
1    0.610237  0.477117  0.915987  0.840819  0.746444
2    0.286369  0.919387  0.769584  0.047926  0.333141
3     0.80648  0.365636  0.898958  0.983921  0.036964
4    0.293454  0.024477  0.706326  0.950589  0.313468
..        ...       ...       ...       ...       ...
329  0.767511  0.935906  0.730144  0.573351  0.041465
330  0.549862  0.156203  0.817324  0.294024  0.831850
331  0.433503  0.703824  0.012962  0.341234  0.182303
332  0.777378  0.264590  0.990195  0.103620  0.372196
333  0.677424  0.515871  0.769076  0.456608  0.929087

[334 rows x 5 columns]

copying a datbase to another database,
changing copy of orginal dataframe does not bring any changes to orginal databbase

In [ ]:
newdf3=newdf.copy() #newdf3=newdf[:]

In [ ]:
newdf3

0         1         2         3         4
0        9876  0.911063  0.408980  0.841196  0.019471
1    0.610237  0.477117  0.915987  0.840819  0.746444
2    0.286369  0.919387  0.769584  0.047926  0.333141
3     0.80648  0.365636  0.898958  0.983921  0.036964
4    0.293454  0.024477  0.706326  0.950589  0.313468
..        ...       ...       ...       ...       ...
329  0.767511  0.935906  0.730144  0.573351  0.041465
330  0.549862  0.156203  0.817324  0.294024  0.831850
331  0.433503  0.703824  0.012962  0.341234  0.182303
332  0.777378  0.264590  0.990195  0.103620  0.372196
333  0.677424  0.515871  0.769076  0.456608  0.929087

[334 rows x 5 columns]

In [ ]:
newdf3[0][0]=1

<ipython-input-52-b40cf156138e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0]=1


In [ ]:
newdf

0         1         2         3         4
0        9876  0.911063  0.408980  0.841196  0.019471
1    0.610237  0.477117  0.915987  0.840819  0.746444
2    0.286369  0.919387  0.769584  0.047926  0.333141
3     0.80648  0.365636  0.898958  0.983921  0.036964
4    0.293454  0.024477  0.706326  0.950589  0.313468
..        ...       ...       ...       ...       ...
329  0.767511  0.935906  0.730144  0.573351  0.041465
330  0.549862  0.156203  0.817324  0.294024  0.831850
331  0.433503  0.703824  0.012962  0.341234  0.182303
332  0.777378  0.264590  0.990195  0.103620  0.372196
333  0.677424  0.515871  0.769076  0.456608  0.929087

[334 rows x 5 columns]

In [ ]:
newdf3

0         1         2         3         4
0           1  0.911063  0.408980  0.841196  0.019471
1    0.610237  0.477117  0.915987  0.840819  0.746444
2    0.286369  0.919387  0.769584  0.047926  0.333141
3     0.80648  0.365636  0.898958  0.983921  0.036964
4    0.293454  0.024477  0.706326  0.950589  0.313468
..        ...       ...       ...       ...       ...
329  0.767511  0.935906  0.730144  0.573351  0.041465
330  0.549862  0.156203  0.817324  0.294024  0.831850
331  0.433503  0.703824  0.012962  0.341234  0.182303
332  0.777378  0.264590  0.990195  0.103620  0.372196
333  0.677424  0.515871  0.769076  0.456608  0.929087

[334 rows x 5 columns]

updating item by using loc(row,col)

In [ ]:
newdf.loc[0,"a"]=6513213

In [ ]:
newdf.head(2)

0         1         2         3         4          a
0   6513213  0.911063  0.408980  0.841196  0.019471  6513213.0
1  0.610237  0.477117  0.915987  0.840819  0.746444        NaN

In [ ]:
newdf.columns=list("abcdef")

In [ ]:
newdf.head(2)

a         b         c         d         e          f
0   6513213  0.911063  0.408980  0.841196  0.019471  6513213.0
1  0.610237  0.477117  0.915987  0.840819  0.746444        NaN

if loc is not present than it make new col and insert the value

In [ ]:
newdf.loc[0,0]=123

In [ ]:
newdf.head()

a         b         c         d         e   f
1  0.610237  0.477117  0.915987  0.840819  0.746444 NaN
2  0.286369  0.919387  0.769584  0.047926  0.333141 NaN
3   0.80648  0.365636  0.898958  0.983921  0.036964 NaN
4  0.293454  0.024477  0.706326  0.950589  0.313468 NaN
5  0.899606  0.756560  0.167367  0.531115  0.002221 NaN

deleting column from dataframe

In [ ]:
newdf=newdf.drop(0,axis=1)

In [ ]:
newdf

a         b         c         d         e   f
1    0.610237  0.477117  0.915987  0.840819  0.746444 NaN
2    0.286369  0.919387  0.769584  0.047926  0.333141 NaN
3     0.80648  0.365636  0.898958  0.983921  0.036964 NaN
4    0.293454  0.024477  0.706326  0.950589  0.313468 NaN
5    0.899606  0.756560  0.167367  0.531115  0.002221 NaN
..        ...       ...       ...       ...       ...  ..
329  0.767511  0.935906  0.730144  0.573351  0.041465 NaN
330  0.549862  0.156203  0.817324  0.294024  0.831850 NaN
331  0.433503  0.703824  0.012962  0.341234  0.182303 NaN
332  0.777378  0.264590  0.990195  0.103620  0.372196 NaN
333  0.677424  0.515871  0.769076  0.456608  0.929087 NaN

[333 rows x 6 columns]

for specific rows and columns

In [ ]:
newdf.loc[[1,2],["c","d"]]

c         d
1  0.915987  0.840819
2  0.769584  0.047926

full column

In [ ]:
newdf.loc[[1,2],:]

a         b         c         d         e   f
1  0.610237  0.477117  0.915987  0.840819  0.746444 NaN
2  0.286369  0.919387  0.769584  0.047926  0.333141 NaN

for all rows

In [ ]:
newdf.loc[:,["d","e"]]

d         e
1    0.840819  0.746444
2    0.047926  0.333141
3    0.983921  0.036964
4    0.950589  0.313468
5    0.531115  0.002221
..        ...       ...
330  0.294024  0.831850
331  0.341234  0.182303
332  0.103620  0.372196
333  0.456608  0.929087
0         NaN       NaN

[334 rows x 2 columns]

for obtaining data from database acc to specific condition

In [ ]:
newdf.loc[(newdf['a']<0.3) & (newdf["c"]>0.1)]

a         b         c         d         e   f
2    0.286369  0.919387  0.769584  0.047926  0.333141 NaN
4    0.293454  0.024477  0.706326  0.950589  0.313468 NaN
6    0.293742  0.266324  0.761514  0.794848  0.657157 NaN
7    0.151984  0.990941  0.108034  0.641589  0.080161 NaN
9    0.239472  0.577444  0.892457  0.473652  0.484570 NaN
..        ...       ...       ...       ...       ...  ..
308  0.090873  0.836217  0.554605  0.499067  0.596492 NaN
317  0.195707  0.447554  0.724104  0.127400  0.564674 NaN
319  0.024818  0.752441  0.366048  0.099944  0.861708 NaN
325  0.028144  0.415315  0.281591  0.278157  0.654766 NaN
326  0.236017  0.542311  0.188903  0.425248  0.401448 NaN

[77 rows x 6 columns]

In [ ]:
newdf.head(2)

a         b         c         d         e   f
1  0.610237  0.477117  0.915987  0.840819  0.746444 NaN
2  0.286369  0.919387  0.769584  0.047926  0.333141 NaN

we use loc if we want to search by name,
and we use iloc if acc to index

iloc-just like loc but here index is used in place of name

In [ ]:
newdf.iloc[0,4]

0.7464438070035098

In [ ]:
newdf.iloc[[0,1],[1,2]]

b         c
1  0.477117  0.915987
2  0.919387  0.769584

In [ ]:
newdf.head(3)

In [ ]:
newdf.drop([0])

a         b         c         d         e   f
1    0.610237  0.477117  0.915987  0.840819  0.746444 NaN
2    0.286369  0.919387  0.769584  0.047926  0.333141 NaN
3     0.80648  0.365636  0.898958  0.983921  0.036964 NaN
4    0.293454  0.024477  0.706326  0.950589  0.313468 NaN
5    0.899606  0.756560  0.167367  0.531115  0.002221 NaN
..        ...       ...       ...       ...       ...  ..
329  0.767511  0.935906  0.730144  0.573351  0.041465 NaN
330  0.549862  0.156203  0.817324  0.294024  0.831850 NaN
331  0.433503  0.703824  0.012962  0.341234  0.182303 NaN
332  0.777378  0.264590  0.990195  0.103620  0.372196 NaN
333  0.677424  0.515871  0.769076  0.456608  0.929087 NaN

[333 rows x 6 columns]

inplace=true means the changes also take place in orginal dataframe

In [ ]:
newdf.drop(['a',"c"],axis=1,inplace=True)

In [ ]:
newdf

b         d         e   f
1    0.477117  0.840819  0.746444 NaN
2    0.919387  0.047926  0.333141 NaN
3    0.365636  0.983921  0.036964 NaN
4    0.024477  0.950589  0.313468 NaN
5    0.756560  0.531115  0.002221 NaN
..        ...       ...       ...  ..
330  0.156203  0.294024  0.831850 NaN
331  0.703824  0.341234  0.182303 NaN
332  0.264590  0.103620  0.372196 NaN
333  0.515871  0.456608  0.929087 NaN
0         NaN       NaN       NaN NaN

[334 rows x 4 columns]

In [ ]:
newdf.drop([0,5],axis=0,inplace=True)

In [ ]:
newdf.head(5)

b         d         e   f
1  0.477117  0.840819  0.746444 NaN
2  0.919387  0.047926  0.333141 NaN
3  0.365636  0.983921  0.036964 NaN
4  0.024477  0.950589  0.313468 NaN
6  0.266324  0.794848  0.657157 NaN

reset_index*****index start from 0 and maintain its order until last,

and also add one column name index containing previous indexes

In [ ]:
newdf.reset_index()

index         b         d         e   f
0        1  0.477117  0.840819  0.746444 NaN
1        2  0.919387  0.047926  0.333141 NaN
2        3  0.365636  0.983921  0.036964 NaN
3        4  0.024477  0.950589  0.313468 NaN
4        6  0.266324  0.794848  0.657157 NaN
..     ...       ...       ...       ...  ..
327    329  0.935906  0.573351  0.041465 NaN
328    330  0.156203  0.294024  0.831850 NaN
329    331  0.703824  0.341234  0.182303 NaN
330    332  0.264590  0.103620  0.372196 NaN
331    333  0.515871  0.456608  0.929087 NaN

[332 rows x 5 columns]

if we do not want index col to add on index reseting

In [ ]:
newdf.reset_index(drop=True)

b         d         e   f
0    0.477117  0.840819  0.746444 NaN
1    0.919387  0.047926  0.333141 NaN
2    0.365636  0.983921  0.036964 NaN
3    0.024477  0.950589  0.313468 NaN
4    0.266324  0.794848  0.657157 NaN
..        ...       ...       ...  ..
327  0.935906  0.573351  0.041465 NaN
328  0.156203  0.294024  0.831850 NaN
329  0.703824  0.341234  0.182303 NaN
330  0.264590  0.103620  0.372196 NaN
331  0.515871  0.456608  0.929087 NaN

[332 rows x 4 columns]

isna or isnull-------return True where value is missing

In [ ]:
newdf["b"].isna()

1      False
2      False
3      False
4      False
6      False
       ...  
329    False
330    False
331    False
332    False
333    False
Name: b, Length: 332, dtype: bool

In [ ]:
newdf["b"].isnull()

1      False
2      False
3      False
4      False
6      False
       ...  
329    False
330    False
331    False
332    False
333    False
Name: b, Length: 332, dtype: bool

changing col value to none

In [ ]:
newdf["b"]=None

In [ ]:
newdf

b         d         e   f
1    None  0.840819  0.746444 NaN
2    None  0.047926  0.333141 NaN
3    None  0.983921  0.036964 NaN
4    None  0.950589  0.313468 NaN
6    None  0.794848  0.657157 NaN
..    ...       ...       ...  ..
329  None  0.573351  0.041465 NaN
330  None  0.294024  0.831850 NaN
331  None  0.341234  0.182303 NaN
332  None  0.103620  0.372196 NaN
333  None  0.456608  0.929087 NaN

[332 rows x 4 columns]

In [ ]:
newdf["b"].isnull()

1      True
2      True
3      True
4      True
6      True
       ... 
329    True
330    True
331    True
332    True
333    True
Name: b, Length: 332, dtype: bool

always use loc because directly it change sometime and sometime not

In [ ]:
newdf.loc[:,["b"]]=54

In [ ]:
newdf

b         d         e   f
1    54  0.840819  0.746444 NaN
2    54  0.047926  0.333141 NaN
3    54  0.983921  0.036964 NaN
4    54  0.950589  0.313468 NaN
6    54  0.794848  0.657157 NaN
..   ..       ...       ...  ..
329  54  0.573351  0.041465 NaN
330  54  0.294024  0.831850 NaN
331  54  0.341234  0.182303 NaN
332  54  0.103620  0.372196 NaN
333  54  0.456608  0.929087 NaN

[332 rows x 4 columns]

In [ ]:
df=pd.DataFrame({"name":["arun","arun","ravi"],
                  "toy":[np.nan,np.nan,np.nan],
                 "born":[pd.NaT,pd.Timestamp("1940-04-25"),pd.NaT]})

In [ ]:
df

name  toy       born
0  arun  NaN        NaT
1  arun  NaN 1940-04-25
2  ravi  NaN        NaT

how="all"------drop null value only when all are null

In [ ]:
df.dropna(how="all",axis=1)

name       born
0  arun        NaT
1  arun 1940-04-25
2  ravi        NaT

In [ ]:
df

name  toy       born
0  arun  NaN        NaT
1  arun  NaN 1940-04-25
2  ravi  NaN        NaT

drop_duplicate-------use to drop duplicate values

keep=first------keep first row
keep=last------keep last row
keep=false-----keep nothing

In [ ]:
df.drop_duplicates(subset=["name"],keep="first")

name  toy born
0  arun  NaN  NaT
2  ravi  NaN  NaT

In [ ]:
df.drop_duplicates(subset=["name"],keep="last")

name  toy       born
1  arun  NaN 1940-04-25
2  ravi  NaN        NaT

In [ ]:
df.drop_duplicates(subset=["name"],keep=False)

name  toy born
2  ravi  NaN  NaT

shape---no of row,col

In [ ]:
df.shape

(3, 3)

info---information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   name    3 non-null      object        
 1   toy     0 non-null      float64       
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 200.0+ bytes


value_count-----for counting values

In [ ]:
df["name"].value_counts(dropna=False)

name
arun    2
ravi    1
Name: count, dtype: int64

notnull=give True if value is not null

In [ ]:
df.notnull()

name    toy   born
0  True  False  False
1  True  False   True
2  True  False  False

create a dataframe of itegers 3 rows and 2 col and run following method

df.decribe()
df.mean()
  df.corr()
df.count()
df.max()
df.min()
df.median()
df.std()




In [ ]:
data={
    "name":["harry","rohan","skillf","shubh"],
    "marks":[92,34,24,17],
    "city":['rampur',"kolkata","bareily",'antartica']
}

In [ ]:
data1=pd.DataFrame(data)

In [ ]:
data1


name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24    bareily
3   shubh     17  antartica

loc fun---if rows/col are continuous

In [ ]:
data1.loc[0:3,"name":"city"]

name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24    bareily
3   shubh     17  antartica

loc fun----if rows/col are not continuous

In [ ]:
data1.loc[[0,3],["name","city"]]

name       city
0  harry     rampur
3  shubh  antartica

we use loc fun if we want cond on col ,oterwise we use directly

condition only on rows

condition on rows and col both
we have to use loc func

In [ ]:
data1[(data1["name"]=='harry') & (data1["marks"]>50)]

name  marks    city
0  harry     92  rampur

In [ ]:
newdf

b         d         e   f
1    54  0.840819  0.746444 NaN
2    54  0.047926  0.333141 NaN
3    54  0.983921  0.036964 NaN
4    54  0.950589  0.313468 NaN
6    54  0.794848  0.657157 NaN
..   ..       ...       ...  ..
329  54  0.573351  0.041465 NaN
330  54  0.294024  0.831850 NaN
331  54  0.341234  0.182303 NaN
332  54  0.103620  0.372196 NaN
333  54  0.456608  0.929087 NaN

[332 rows x 4 columns]

group give diffent vlues due to null values

In [ ]:
newdf.groupby(["b"]).count()

d    e  f
b              
54  332  332  0

#numpy

In [ ]:
import numpy as np

creating an array

In [ ]:
myarr=np.array([3,6,32,7])

In [ ]:
myarr

array([ 3,  6, 32,  7])

creating array with datatype

In [ ]:
myarr=np.array([[3,6,32,7]],np.int8)

In [ ]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

accessing element in array

In [ ]:
myarr[0,1]

6

shape

In [ ]:
myarr.shape


(1, 4)

checking datatype

In [ ]:
myarr.dtype

dtype('int8')

inserting an element

In [ ]:
myarr[0,1]=45

In [ ]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

size of array

In [ ]:
myarr.size

4

#array creation metods
There are 6 general mechanisms for creating arrays:

1--Conversion from other Python structures (i.e. lists and tuples)

2--Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3--Replicating, joining, or mutating existing arrays

4--Reading arrays from disk, either from standard or custom formats

5--Creating arrays from raw bytes through the use of strings or buffers

6--Use of special library functions (e.g., random)

1--Conversion from other Python structures (i.e. lists and tuples)

In [ ]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [ ]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [ ]:
listarray.size

9

In [ ]:
np.array({34,23,23})

array({34, 23}, dtype=object)

2--Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

these are the functions numpy give us

In [ ]:
zeros=np.zeros((2,5))

In [ ]:
zeros,zeros.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 dtype('float64'))

In [ ]:
rng=np.arange(5,8)

In [ ]:
rng

array([5, 6, 7])

In [ ]:
lspace=np.linspace(1,5,12)

In [ ]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
emp=np.empty((4,6))

In [ ]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
ide=np.identity(5)

In [ ]:
ide,ide.shape

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 (5, 5))

In [ ]:
ones=np.ones(5)

In [ ]:
ones

array([1., 1., 1., 1., 1.])

In [ ]:
arr=np.arange(99)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr=arr.reshape(3,33)

In [ ]:
arr.shape,arr

((99,),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]))

In [ ]:
arr.reshape(3,31)

ValueError: ignored

it only work when all element fit in array properly after reshaping

In [ ]:
arr=arr.ravel()

In [ ]:
arr.shape

(99,)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

numpy axis

In [ ]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [ ]:
ar=np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])

In [ ]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
ar.sum()

29

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
ar.ndim

2

In [ ]:
ar.size

9

In [ ]:
ar.nbytes

72

In [ ]:
one=np.array([1,3,4,634,2])

In [ ]:
one.argmax()

3

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()

array([0, 4, 1, 2, 3])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.argmin()

8

In [ ]:
ar.argmax()

6

In [ ]:
ar.argmax(axis=0)

array([2, 1, 1])

In [ ]:
ar.argmax(axis=1)

array([2, 2, 0])

In [ ]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
ar.argsort(axis=1)


array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
ar.argsort(axis=0)


array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar2=np.array([[1,2,1],
            [4,0,6],
             [8,1,0]])

In [ ]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [ ]:
[1,23,3]+[1,2,3]

[1, 23, 3, 1, 2, 3]

In [ ]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [ ]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [ ]:
ar//ar2

<ipython-input-110-ad4ea5ce5418>:1: RuntimeWarning: divide by zero encountered in floor_divide
  ar//ar2


array([[1, 1, 3],
       [1, 0, 1],
       [0, 1, 0]])

In [ ]:
ar%ar2

<ipython-input-111-8017fe3c7c88>:1: RuntimeWarning: divide by zero encountered in remainder
  ar%ar2


array([[0, 0, 0],
       [0, 0, 0],
       [7, 0, 0]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [ ]:
np.where(5)

(array([0]),)

In [ ]:
np.count_nonzero(ar)

8

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
import sys

In [ ]:
py_ar=[0,4,55,2]

In [ ]:
np_ar=np.array(py_ar)

In [ ]:
sys.getsizeof(1)*len(py_ar)

112

In [ ]:
np_ar.itemsize*np_ar.size

32

In [ ]:
np_ar.tolist()

[0, 4, 55, 2]